In [1]:
import numpy as np

In [2]:
#set seed fore reproducibility -for recieving exact same result for random function in code everytime
np.random.seed(seed =20)

In [3]:
#Scalar:
x = np.array(6)
print("x:",x)
print("dim of x:",x.ndim)  #number of dim
print("x shape:",x.shape) #dim
print("x size:",x.size) #size of elements
print("x dtype:",x.dtype) #data type

x: 6
dim of x: 0
x shape: ()
x size: 1
x dtype: int64


In [4]:
#vector
x = np.array([1.3,2.2,1.7])
print("x:",x)
print("dim of x:",x.ndim)  #number of dim
print("x shape:",x.shape) #dim
print("x size:",x.size) #size of elements
print("x dtype:",x.dtype) #data type

x: [1.3 2.2 1.7]
dim of x: 1
x shape: (3,)
x size: 3
x dtype: float64


In [5]:
#Matrix
x =np.array([[1,2,6.4],[3,4,5]])
# x = np.array([[1,2],[3,4,5]]) #this will give error need homogenous shape
print("x:\n",x)
print("dim of x:",x.ndim)  #number of dim
print("x shape:",x.shape) #dim
print("x size:",x.size) #size of elements
print("x dtype:",x.dtype) #data type

x:
 [[1.  2.  6.4]
 [3.  4.  5. ]]
dim of x: 2
x shape: (2, 3)
x size: 6
x dtype: float64


In [6]:
#3D tensor
x = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("x:\n",x)
print("dim of x:",x.ndim)  #number of dim
print("x shape:",x.shape) #dim
print("x size:",x.size) #size of elements
print("x dtype:",x.dtype) #data type
print("x[0]:\n",x[0])

x:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
dim of x: 3
x shape: (2, 2, 2)
x size: 8
x dtype: int64
x[0]:
 [[1 2]
 [3 4]]


In [7]:
#Function for tensors
print(np.zeros((2,2)))
print("\n")
print(np.ones((2,2)))
print("\n")
print(np.eye((2))) #Identity matrix
print("\n")
print(np.random.random((2,2)))

[[0. 0.]
 [0. 0.]]


[[1. 1.]
 [1. 1.]]


[[1. 0.]
 [0. 1.]]


[[0.5881308  0.89771373]
 [0.89153073 0.81583748]]


In [8]:
#Indexing
#Slicing
x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)
print("col 1:", x[:,1])
print("row 0:",x[0,])
print("row 0,1 and col 1,2:\n",x[0:2,1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
col 1: [ 2  6 10]
row 0: [1 2 3 4]
row 0,1 and col 1,2:
 [[2 3]
 [6 7]]


In [9]:
#Integer array index
print(x)
print("\n")
row_index_num = np.array([0,1,2])
col_index_num =np.array([0,2,1])
print(x[row_index_num,col_index_num]) #this will print [x[0,0],x[1,2],x[2,1]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[ 1  7 10]


In [10]:
#Boolean array indeing
x = np.array([[1,2],[3,4],[5,6]])
print("x:\n",x)
print("x>2:\n",x>2)
print("x[x>2]:\n",x[x>2]) #numpy looks at every position where the mask is True and extract those values(mask = x>2 x[mask])

x:
 [[1 2]
 [3 4]
 [5 6]]
x>2:
 [[False False]
 [ True  True]
 [ True  True]]
x[x>2]:
 [3 4 5 6]


In [11]:
#Arithmatic -Basic Math
x = np.array([[1,2],[3,4]],dtype=np.float64)
y = np.array([[1,2],[3,4]],dtype=np.float64)
print(np.add(x,y)) 
print("\n")
print(np.subtract(x,y))
print("\n")
print(np.multiply(x,y))
print((np.multiply(x,y)).dtype)
print(type(np.multiply(x,y)))

[[2. 4.]
 [6. 8.]]


[[0. 0.]
 [0. 0.]]


[[ 1.  4.]
 [ 9. 16.]]
float64
<class 'numpy.ndarray'>


In [12]:
#Dot product
a = np.array([[1,2,3],[4,5,6]],dtype=np.float64)
b = np.array([[7,8],[9,10],[4,6]])
c = a.dot(b)
print(f"{a.shape}.{b.shape} ={c.shape}")
# print("\n")
print(c)

(2, 3).(3, 2) =(2, 2)
[[ 37.  46.]
 [ 97. 118.]]


In [13]:
#Axis Operation
x = np.array([[1,2],[3,4]])
print(x)
# print("\n")
print(np.sum(x)) #add all elements
# print("\n")
print(np.sum(x,axis=0)) #sum accross rows
# print("\n")
print(np.sum(x,axis=1)) #sum accross colums

[[1 2]
 [3 4]]
10
[4 6]
[3 7]


In [14]:
#Min/Max
x = np.array([[1,2,3],[4,5,6]])
print(x.min())
print(x.max())
print(x.min(axis=0)) #compare rows and find min 
print(x.min(axis=1)) #compare colmunns

1
6
[1 2 3]
[1 4]


In [15]:
#Broadcast - when we try to do operations on tensors with incompatible shapes.It got broadcasted to math the dim of bigger vector
x = np.array([1,2])
y = np.array(3)
z = x+y
L = x+3
print(z)
print(L)
print(type(x))
print(type(y))
print(type(3))

[4 5]
[4 5]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'int'>


In [16]:
#Gotches
a = np.array((3,4,5))
b = np.expand_dims(a,axis=0)
c = a+b
d = np.expand_dims(a,axis=1)
e = a+d
print(a)
# print(type(a))
# print(a.shape)
print(b)
# print(type(b))
# print(b.shape)
print(c)
# print(type(c))
# print(c.shape)
print(d)
# print(type(d))
# print(d.shape)
print(e)
# print(type(e))
# print(e.shape)

[3 4 5]
[[3 4 5]]
[[ 6  8 10]]
[[3]
 [4]
 [5]]
[[ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]]


In [17]:
a = np.array((3, 4, 5))
b = np.expand_dims(a, axis=1)
c = a + b
print(c)

[[ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]]


In [18]:
#for fixing unintentional broadcasting behavour we have to make sure that a is same shape as b

print(a)
print(b)
a = a.reshape(-1,1)
a.shape
print(a)
c = a+b
c.shape
print(c)

[3 4 5]
[[3]
 [4]
 [5]]
[[3]
 [4]
 [5]]
[[ 6]
 [ 8]
 [10]]


In [19]:
#it happen more often when we create an array from lista = np.array([3,4,5])
print(a.shape)
#1 specifiy that new array must have exactly one column,-1 acts as wildcard/unknown dimension(to automatically calculate the exact number of rows needed based on total number of elements in the original array
a = a.reshape(-1,1)
print(a.shape)

(3, 1)
(3, 1)


In [20]:
#Transpose
x = np.array([[1,2,3],[4,5,6]])
print(x)
print(x.shape)
y = np.transpose(x,(1,0))
print(y)
print(y.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [21]:
#Reshape:
x = np.array([[1,2,3,4,5,6]])
print(x)
print(x.shape)
print("\n")
y = np.reshape(x,(2,3))
print(y)
print(y.shape)
print("\n")
z = np.reshape(x,(2,-1))
print(z)
print(z.shape)
print("\n")

[[1 2 3 4 5 6]]
(1, 6)


[[1 2 3]
 [4 5 6]]
(2, 3)


[[1 2 3]
 [4 5 6]]
(2, 3)




In [22]:
#Unintended reshaping -we want other way reshaping 
x = np.array([[[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3]],
            [[10, 10, 10, 10], [20, 20, 20, 20], [30, 30, 30, 30]]])
print ("x:\n", x)
print ("x.shape: ", x.shape)
z_incorrect = np.reshape(x,(x.shape[1],-1))
print ("z_incorrect:\n", z_incorrect)
print ("z_incorrect.shape: ", z_incorrect.shape)

x:
 [[[ 1  1  1  1]
  [ 2  2  2  2]
  [ 3  3  3  3]]

 [[10 10 10 10]
  [20 20 20 20]
  [30 30 30 30]]]
x.shape:  (2, 3, 4)
z_incorrect:
 [[ 1  1  1  1  2  2  2  2]
 [ 3  3  3  3 10 10 10 10]
 [20 20 20 20 30 30 30 30]]
z_incorrect.shape:  (3, 8)


In [23]:
#Inteded reshpaing
#make axis 1 become the new axis 0,axis 0 become the new axis 1 and keep axis 2 where it is
y = np.transpose(x,(1,0,2))
print(y)
print(y.shape)
z_correct= np.reshape(y,(y.shape[0],-1))
print(z_correct)
print(z_correct.shape)

[[[ 1  1  1  1]
  [10 10 10 10]]

 [[ 2  2  2  2]
  [20 20 20 20]]

 [[ 3  3  3  3]
  [30 30 30 30]]]
(3, 2, 4)
[[ 1  1  1  1 10 10 10 10]
 [ 2  2  2  2 20 20 20 20]
 [ 3  3  3  3 30 30 30 30]]
(3, 8)


In [24]:
#Joining
x = np.random.random((2,3))
print(x)
print(x.shape)

[[0.03588959 0.69175758 0.37868094]
 [0.51851095 0.65795147 0.19385022]]
(2, 3)


In [25]:
#concatenation
y = np.concatenate([x,x],axis=0)
print(y)
print(y.shape)

[[0.03588959 0.69175758 0.37868094]
 [0.51851095 0.65795147 0.19385022]
 [0.03588959 0.69175758 0.37868094]
 [0.51851095 0.65795147 0.19385022]]
(4, 3)


In [26]:
#stacking
z = np.stack([x,x],axis=1)
print(z)
print(z.shape)

[[[0.03588959 0.69175758 0.37868094]
  [0.03588959 0.69175758 0.37868094]]

 [[0.51851095 0.65795147 0.19385022]
  [0.51851095 0.65795147 0.19385022]]]
(2, 2, 3)


In [27]:
#Expanding/reducing
#Adding dimensions
x = np.array([[1,2,3],[4,5,6]])
print(x)
print(x.shape)
y = np.expand_dims(x,1)
print("\n")
print(y)
print("\n")
print(y.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


[[[1 2 3]]

 [[4 5 6]]]


(2, 1, 3)


In [28]:
#remove dimensions
x = np.array([[[[1,2,3]]],[[[4,5,6]]]])
print(x)
print(x.shape)
y = np.squeeze(x,1)
print(y)
print(y.shape)

[[[[1 2 3]]]


 [[[4 5 6]]]]
(2, 1, 1, 3)
[[[1 2 3]]

 [[4 5 6]]]
(2, 1, 3)


In [29]:
#References:
# @article{madewithml,
#     author       = {Goku Mohandas},
#     title        = { NumPy - Made With ML },
#     howpublished = {\url{https://madewithml.com/}},
#     year         = {2023}
# }